stages:
  - assume_role
  - login
  - build-and-push

variables:
  AWS_ACCOUNT_ID: "123456789101"
  AWS_REGION: "us-east-2"
  ECR_REPOSITORY: "projectapp"
  ECR_REGISTRY: "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com"
  IMAGE_TAG: "$CI_COMMIT_SHA"

login_to_aws:
  stage: login
  script:
    - export AWS_ACCESS_KEY_ID="${AWS_ACCESS_KEY_ID}"
    - export AWS_SECRET_ACCESS_KEY="${AWS_SECRET_ACCESS_KEY}"
    - $(aws ecr get-login --no-include-email | docker login --username AWS --password-stdin $ECR_REGISTRY)

build_and_push_to_ecr:
  stage: build-and-push
  image: docker:19.03.12
  dependencies:
    - login_to_aws
  script:
    # Build the Docker image
    - docker build --build-arg NEXTAUTH_SECRET=$NEXTAUTH_SECRET --build-arg NEXTAUTH_URL=$NEXTAUTH_URL --build-arg GOOGLE_CLIENT_ID=$GOOGLE_CLIENT_ID --build-arg GOOGLE_CLIENT_SECRET=$GOOGLE_CLIENT_SECRET --build-arg DB_NAME=$DB_NAME --build-arg MONGODB_URI=$MONGODB_URI -t $IMAGE_NAME .
    # Push the Docker image to ECR
    - docker push $IMAGE_NAME
